services:
  bot:
    build: .
    container_name: gitlab-notification-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/app/logs
